### PR TITLE
remove undefined runDbBuild and update instructions

### PR DESCRIPTION
**Pull request by mattlub**
- removes undefined `runDbBuild` variable, and `module.exports` from `db_build` (relates #11).  Now this file reflects better the file created in the previous workshop.

- updates the README instructions.

- This doesn't include instructions for a `run_db_build` file (as was mentioned in #11) because it is not needed at the moment. (README currently instructs students to run the build script inside psql)

- removes unused `eslint` dep to fix npm insecure package warnings

### CODE REVIEW

**Comment by eliascodes** [comment]
@mattlub Looks good. Would it be cheeky to ask for the insecure dependencies to be taken care of with this PR too?

**Comment by mattlub** [comment]
@eliascodes I will do it in a different PR because the dependencies could also do with a cleanup

**Comment by mattlub** [comment]
@eliascodes actually I did it here, just removed eslint

**Comment by m4v15** [comment]
@mattlub will merge after resolution

**Comment by mattlub** [comment]
Hi @developess, if you and the other London mentors are happy to merge this we'll do it. It includes minor changes, most of the lines changed are in the package-lock.

If not, it's ok, we can deliver it in Khalil from a forked version.

**Comment by developess** [comment]
@mattlub feel free to merge! Thanks

**Pull request merged**
